version: "3"
services:
  nginx:
    image: nginx:latest
    restart: "always"
    ports:
      - "3000:80"
    volumes:
      - ./config/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    labels:
      - traefik.http.middlewares.app-https-redirect.redirectscheme.scheme=https

      - "traefik.http.routers.nginx.rule=Host(`domain.com`)"
      - traefik.http.routers.nginx.entrypoints=web
      - traefik.http.routers.nginx.middlewares=app-https-redirect

      - "traefik.http.routers.nginx-secure.rule=Host(`domain.com`)"
      - traefik.http.routers.nginx-secure.entrypoints=secure
      - traefik.http.routers.nginx-secure.tls=true
      - traefik.http.routers.nginx-secure.tls.certresolver=default
      - traefik.http.routers.nginx-secure.service=nginx-secure-service
      - traefik.http.services.nginx-secure-service.loadbalancer.server.port=80

  traefik:
    image: traefik:latest
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/acme.json:/etc/traefik/acme.json
      - ./log:/opt/log
